In [5]:
#How create Array using Numpy

In [27]:
import numpy as np
arr = np.array([10,18,161,19,28])
print(arr)
print(type(arr))

[ 10  18 161  19  28]
<class 'numpy.ndarray'>


In [61]:
# lets make metrix of array
import numpy as np
arr = np.array([[10,18,161,19,28],[10,18,161,19,28],[10,18,161,19,28],[10,18,161,19,28]])
print(arr)


[[ 10  18 161  19  28]
 [ 10  18 161  19  28]
 [ 10  18 161  19  28]
 [ 10  18 161  19  28]]


In [63]:
# Slicing in array

In [97]:
import numpy as np
arr = np.array([[10,18,161,19,28],[10,18,161,19,28]])
print(arr[1:4,2:4])

print(np.shape(arr))
print(np.size(arr))


[[161  19]]
(2, 5)
10


In [99]:
# There are some functions to Inspect arrays

In [121]:
import numpy as np
arr = np.array([10,18,161,19,28])
print(arr)
print(type(arr)) #Type will show us data type
print(np.shape(arr)) # will tell us shape
print(np.size(arr)) # will tell us size
print(np.ndim(arr)) # Dimansion of array
print(len(arr)) # Len of array
print(arr.astype(str)) # convert array into different type



[ 10  18 161  19  28]
<class 'numpy.ndarray'>
(5,)
5
1
5
['10' '18' '161' '19' '28']
<class 'numpy.ndarray'>


In [123]:
#Loops and Functions

In [133]:
res = []
temp = [2,4,6,8]
for i in temp:
  res.append(2*i) # This will multiply each number in temp by 2
res

[4, 8, 12, 16]

In [135]:
# List comprehension way

In [139]:
[2*x for x in temp]

[4, 8, 12, 16]

In [215]:
# Using numpy

In [294]:
# Here we have a simple List
distance = [45,23,34]
speed = [5,32,77]
print(type([distance, speed]))

<class 'list'>


In [308]:
import numpy as array
import numpy as arrange

In [310]:
# Lets convert the List into Arrays
dist = np.array(distance)
spd = np.array(speed)
print (dist)
print (spd)
time = dist/spd
print (time)
type(time)

[45 23 34]
[ 5 32 77]
[9.         0.71875    0.44155844]


numpy.ndarray

In [312]:
# Airthmetic Operations

In [314]:
a = np.array([1,2,3,4,5,6])
b = np.array([10,20,30,40,50,60])
print (a+b)  
a*b
a-b

[11 22 33 44 55 66]


array([ -9, -18, -27, -36, -45, -54])

In [316]:
#Arrange method

In [330]:
c = np.arange(15)
print(c)

d = np.arange(5,56,5)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 5 10 15 20 25 30 35 40 45 50 55]


In [332]:
# Using linspace

In [334]:
e = np.linspace(3,100,5)
print(e)

[  3.    27.25  51.5   75.75 100.  ]


In [ ]:
# Use reshape (It is used to create dimensions)

In [370]:
f = np.array([1,2,3,4,5,6,7,8,9,0,0,99,88,77,66,55,55,44,34,23])
print(f)
g = f.reshape(5,4)
print(g)
h = f.reshape(2,2,5)
print(h)

[ 1  2  3  4  5  6  7  8  9  0  0 99 88 77 66 55 55 44 34 23]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  0  0 99]
 [88 77 66 55]
 [55 44 34 23]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9  0]]

 [[ 0 99 88 77 66]
  [55 55 44 34 23]]]


In [ ]:
# Making Ones and Zero

In [388]:
s = np.ones(5)
print(s)
j = np.zeros(5)
print(j)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


In [390]:
# Create Identity matrix

In [398]:
l = np.eye(6)
print(l)
r = np.eye(5,6)
print(r)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [267]:
import pandas as pd
pd = pd.read_csv("store_sales.csv")
pd.tail()

array([ 10,  40,  90, 160, 250, 360])

In [285]:
import numpy as np
import pandas as pd
def bonus_func(sales_col):
    elig_values = np.where(sales_col > 10, "eligible", "not eligible")
    return elig_values
#store_sales["Jan_Bonus"] = bonus_func(store_sales["Jan"])
#store_sales

#Using apply method 
newdf = store_sales.select_dtypes(include = ["int64","float64"]).apply(bonus_func)
newdf
vanshu = pd.concat([store_sales,newdf],axis = 1)

vanshu

store_id        city  Jan  Feb  Mar  Apr  May  Jun July Aug  ...  \
0       S_1       Texas    8   20   13   21   17   20   24  17  ...   
1       S_2  California   12   19   15   15   11   19    7  15  ...   
2       S_3  California   16   16   14   19   23    6   13  13  ...   
3       S_4       Texas    8   18   13   10   14   14    6   8  ...   
4       S_5       Texas   19    5   24    9    5   24   10   5  ...   
..      ...         ...  ...  ...  ...  ...  ...  ...  ...  ..  ...   
95     S_96       Texas    7   10   20   20   10   15   15  21  ...   
96     S_97  California   13    6    7   15   22   10   21  23  ...   
97     S_98       Texas   16    9    6   14   20   13   11  10  ...   
98     S_99     Arizona   18   16    9    5   12   22   11  13  ...   
99    S_100  California    5   23   17   24   15   21   19  10  ...   

             Mar           Apr           May           Jun          July  \
0       eligible      eligible      eligible      eligible      eligible   
1       eligible      eligible      eligible      eligible  not eligible   
2       eligible      eligible      eligible  not eligible      eligible   
3       eligible  not eligible      eligible      eligible  not eligible   
4       eligible  not eligible  not eligible      eligible  not eligible   
..           ...           ...           ...           ...           ...   
95      eligible      eligible  not eligible      eligible      eligible   
96  not eligible      eligible      eligible  not eligible      eligible   
97  not eligible      eligible      eligible      eligible      eligible   
98  not eligible  not eligible      eligible      eligible      eligible   
99      eligible      eligible      eligible      eligible      eligible   

             Aug           Sep           Oct           Nov           Dec  
0       eligible      eligible  not eligible  not eligible  not eligible  
1       eligible  not eligible      eligible      eligible      eligible  
2       eligible      eligible      eligible      eligible  not eligible  
3   not eligible  not eligible      eligible  not eligible      eligible  
4   not eligible      eligible      eligible  not eligible      eligible  
..           ...           ...           ...           ...           ...  
95      eligible      eligible  not eligible      eligible      eligible  
96      eligible  not eligible  not eligible      eligible  not eligible  
97  not eligible  not eligible      eligible      eligible      eligible  
98      eligible      eligible      eligible      eligible  not eligible  
99  not eligible      eligible      eligible  not eligible  not eligible  

[100 rows x 27 columns]